### ISSUE TITLE
how to add a new emoji to the list?

### ISSUE THREAD

**Issue by woshichuanqilz** [ryanSN/winmoji#128]
I found more emoji here so I want to add them to them,  Or how to add my custom emoji to the list? 
https://getemoji.com/

**Comment by ryanSN** [comment]
Hi, currently the application does not allow setting your own emojis as it is based on the Unicode support in windows.  The package I currently use is very outdated but has a beta build with some of the new emojis. 

My plan is to build an emoji library that will use the official list of emojis found here http://unicode.org/emoji/charts/full-emoji-list.html to take winmoji off the dependency of the other package.

**Comment by tylerkilburn** [comment]
Ryan, I could scrape that page and dump to a json for Root.js to pull in.  With your permission, may I fire up a branch to start taking a stab at it and shaping the data to what emojilib.lib provides?  A couple things have me wondering.  1. Those CLDR Short Names will need some aliases  2. I am not super familiar with what windows can support.  Is everything on  http://unicode.org/emoji/charts/full-emoji-list.html fair game?

**Comment by tylerkilburn** [comment]
Setup the scrape project https://gitlab.com/tkil/emoji-scrape , let me know if you are interest and I will wrap it up and at worst case at least get you a JSON that looks like what emoji lib is providing.

**Comment by ryanSN** [comment]
Hi @tylerkilburn thanks for the repo.  I actually had another idea in mind based on repo I star'd awhile ago (https://github.com/milesj/emojibase) This would provide much needed translation support winmoji needs as well I could build this into the build pipeline to always scrape for the latest emojis on winmoji release.

I just can't use this out of the box because of the data schema winmoji is using, so I would need to tweak this a bit. Just not on the top of my to-do list at the moment, mainly because Windows doesn't update their support for emojis that often. Also unicode won't have all the alias's I need / categories when searching so will need to build some trickery there. 

Not everything on full-emojis is fair game. Example windows doesn't support `smiling face with tear`, But simple enough to filter our while scraping.

**Comment by tylerkilburn** [comment]
Gotcha, this makes sense.  Thanks for the feedback.  I don't want to chase a dead end on this one and step on your toes.  Do you have anything else that needs chipping in?

**Comment by ryanSN** [comment]
Closing this issue, 
Windows 10 currently only suppose unicode 12. Which the industry is up to 14 (Soon). 

To the original issue, we are bound by the fonts that Windows 10 comes with and supports. So you are unable to add emojis that are supported on other systems that are not supported by windows.

I have moved away from https://www.npmjs.com/package/emojilib and are now using https://www.npmjs.com/package/winmojilib which will allow me to support future Unicode much better and in a faster state. Future plans around this package are to support the Fitzpatrick scale (skin tons) as well as localization.

Release 2.2.0 supports this new package.
