### ISSUE TITLE
Windows Defender and virustotal.com detect a virus

### ISSUE THREAD

**Issue by halloalexkern** [ryanSN/winmoji#132]
Windows Defender and virustotal.com detect a virus in the release "winMoji-Setup-2.1.0.exe".  

check:https://www.virustotal.com/gui/file/d051c36d9c68c18b84b834d1998069b8d85674fced0a58ed928df0d18b6eb88e/detection

**Comment by ryanSN** [comment]
Thanks for reporting, this is a false positive mainly because the app is unsigned. (signing is $245 @ 3 years which I can't do on a free product that I collect nothing from)
![not-signed](https://user-images.githubusercontent.com/15616532/75778413-baf4cd00-5d25-11ea-9ee7-82e0c5fe6f54.PNG)

Bkav is going "Hey, this program is packed, so I can't see everything it contains at the moment, could have a virus in there."
