### ISSUE TITLE
Suggestion RE: 32bit and "portable"

### ISSUE THREAD

**Issue by Darthagnon** [ryanSN/winmoji#165]
I forked and tested, and found that the 32bit build uses around 30 MB less RAM than the 64bit build. Idea: Why not ditch 64bit and do just 32bit builds? 32bit builds will be compatible with everything and use less RAM, which should be desirable for:
- stuff you might want to start with Windows (like emoji keyboards)
- on older machines with Win7 and less RAM, such as the ones that would need this software because they don't have Win10's emoji keyboard
- Electron programs use a lot of RAM. Any chance to decrease that is desirable.
- smaller installers.

I don't know if there's some important benefit 64bit brings to this type of program...?

### Test results
| arch  |Private WS| Private bytes|
|-------|----------|--------------|
| 32bit | 79.93 MB | 140.16 |
| 64bit | 109.22 MB | 148.6 |

About the "portable" installer - I tested it, and not 100% sure it's worth it (at least for me). Behaviour: Extracts the program files (i.e. installs) them to ```%LocalAppData%\Temp\WinMoji```; they then get deleted when you're done. Might as well run the full installation and not wear down the SSD 200mb at a time with the "portable" installer.

Just my 2 cents.

About the Telemetry 😥 Thank you for being upfront about it. I can understand wanting to know how many people use your stuff. It's less of a problem for me with e.g. websites and online resources, where users actively load your servers. But telemetry in offline software ain't really my cup of tea. Currently, I have "opted out" by forking and ```yarn build```ing a version for personal use without an updater or telemetry.

**Comment by ryanSN** [comment]
Thanks for the feedback and I appreciate you taking the time to write a thorough response. 

I can also break out 32bit and 64bit into their own installers, I had it this way in the past. 
The lowest size I can get this program with Electron is 32mb, and that's mostly due to the fact Chromium packaged within. There was at one point a project to just use the native browser instead of packing up Chromium, I don't think it got anywhere.

 The portable is just there as it takes even less effort for me to make the installer for it, so it's more of a why not. 

This project wasn't made to support Windows 7 that became a side effect. 
When this project was made windows 10 didn't have an emoji support popup, they didn't even have it on the keyboard option. Windows 10 didn't add this till the 2017 release (this project existed before that)

This project was made 4+ years ago as a learning exercise around Electron, if you notice the code, it doesn't have much. Follows very old react patterns and frankly doesn't need react to do what it's doing. 

A future goal is to just expand this project to include typescript, thus focusing the code more. As well as expanding to support configurations, proper groupings, filtering, packaging the emoji font and try to squeeze performance from it. 

The 64bit overall is to future proof it, 32bit applications area already walking the end of life.

I agree about the Telemetry, but that is why I'm gathering very little. I.e. nothing about the system, user, etc... All I gather is a UUID and get nothing else from it.

The plan is and always has been to opt in / out when a configuration page is created. Thie Telemetry call happens only at startup and is very lightweight, you can even block it with a pihole very easily. 


Why do I need this data? to focus on improvements.
An example, a large group of people that use this application are from Russia / Spain / France. This data is not collected in the app, but from downloads, reviews and feedback. 

This is what is driving the 32bit, much like you have stated it's been requested to be returned due to the Windows 7 usage. 
Its also been requested to localize, which can be done with the [winmojilib](https://github.com/ryanSN/winmojilib) project and is being planned out. 


As for the forking to opt-out, this is an MIT licensed project and not BSD for a reason. I'm a one-man show, and as it's an open-source project PRs are more than welcome.

**Comment by Darthagnon** [comment]
Thank you for the explanation! It makes sense. Thank you again for making this project! Apologies if my comments came off as at all acidic or anything.

Can't say I really understand licenses (I really need to read up on them), but if I manage to figure out anything interesting in the fork, I'll be sure to give you a shout.

I didn't realise Win10 came without an emoji panel; I'm still using an ancient version (1709, no updates) and I'd assumed that the emoji panel had been there since the beginning. 

Agreed, 32bit is on its way out, though I remember reading somewhere that Windows-on-ARM can apparently emulate for 32bit (but not for 64bit), but then Electron is a universal platform, so probably already exists natively.

**Comment by ryanSN** [comment]
@Darthagnon , same thanks you so much for the feed back. As well if you build anything that you feel can benefit the application, PR's are totally welcome!
